workaround: l3 plugin misses dvr_deletens_if_no_port method
Although dvr_deletens_if_no_port isn't part of l3 interface,
it's a part of dvr l3 plugin because ml2 plugin calls the method on
l3 plugin. It causes following exception when deleting network.

TODO:
This patch only addresses AttributeError exception so that some tempest
tests pass. Later the method needs to be implemented meaningfully
in order to support dvr.

> Exception during message handling: 'OpenDaylightL3RouterPlugin' object has no attribute 'dvr_deletens_if_no_port'
> Traceback (most recent call last):
> File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 142, in _dispatch_and_reply
> executor_callback))
> File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 186, in _dispatch
> executor_callback)
> File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 130, in _do_dispatch
> result = func(ctxt, **new_args)
> File "/odl/neutron/neutron/api/rpc/handlers/dhcp_rpc.py", line 170, in release_dhcp_port
> plugin.delete_ports_by_device_id(context, device_id, network_id)
> File "/odl/neutron/neutron/db/db_base_plugin_v2.py", line 884, in delete_ports_by_device_id
> self.delete_port(context, port_id)
> File "/usr/local/lib/python2.7/dist-packages/oslo_db/api.py", line 146, in wrapper
> ectxt.value = e.inner_exc
> File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 119, in __exit__
> six.reraise(self.type_, self.value, self.tb)
> File "/usr/local/lib/python2.7/dist-packages/oslo_db/api.py", line 136, in wrapper
> return f(*args, **kwargs)
> File "/odl/neutron/neutron/plugins/ml2/plugin.py", line 1291, in delete_port
> removed_routers = l3plugin.dvr_deletens_if_no_port(
> AttributeError: 'OpenDaylightL3RouterPlugin' object has no attribute 'dvr_deletens_if_no_port'

Change-Id: I3f24df4e99a3df6d968480172f8e31fce119533f
Closes-Bug: #1474265