alembic: db migration fails
the patch of https://review.openstack.org/#/c/390017/ caused the
following exception during db migration.
This patch reverts the migration scripts change of the patch.

> INFO  [alembic.runtime.migration] Running upgrade  -> b89a299e19f9, Initial odl db, branchpoint
> INFO  [alembic.runtime.migration] Running upgrade b89a299e19f9 -> 247501328046, Start of odl expand branch
> INFO  [alembic.runtime.migration] Running upgrade 247501328046 -> 37e242787ae5, Opendaylight Neutron mechanism driver refactor
> INFO  [alembic.runtime.migration] Running upgrade 37e242787ae5 -> 703dbf02afde, Add journal maintenance table
> INFO  [alembic.runtime.migration] Running upgrade 703dbf02afde -> 3d560427d776, add sequence number to journal
>   Running upgrade for neutron ...
>   OK
>   Running upgrade for networking-odl ...
> Traceback (most recent call last):
>   File "/usr/local/bin/neutron-db-manage", line 10, in <module>
>     sys.exit(main())
>   File "/opt/stack/neutron/neutron/db/migration/cli.py", line 687, in main
>     return_val |= bool(CONF.command.func(config, CONF.command.name))
>   File "/opt/stack/neutron/neutron/db/migration/cli.py", line 208, in do_upgrade
>     desc=branch, sql=CONF.command.sql)
>   File "/opt/stack/neutron/neutron/db/migration/cli.py", line 109, in do_alembic_command
>     getattr(alembic_command, cmd)(config, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 174, in upgrade
>     script.run_env()
>   File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 407, in run_env
>     util.load_python_file(self.dir, 'env.py')
>   File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 93, in load_python_file
>     module = load_module_py(module_id, path)
>   File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 79, in load_module_py
>     mod = imp.load_source(module_id, path, fp)
>   File "/opt/stack/networking-odl/networking_odl/db/migration/alembic_migrations/env.py", line 99, in <module>
>     run_migrations_online()
>   File "/opt/stack/networking-odl/networking_odl/db/migration/alembic_migrations/env.py", line 90, in run_migrations_online
>     context.run_migrations()
>   File "<string>", line 8, in run_migrations
>   File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/environment.py", line 797, in run_migrations
>     self.get_context().run_migrations(**kw)
>   File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/migration.py", line 312, in run_migrations
>     step.migration_fn(**kw)
>   File "/opt/stack/networking-odl/networking_odl/db/migration/alembic_migrations/versions/newton/expand/3d560427d776_add_sequence_number_to_journal.py", line 48, in upgrade
>     onupdate=sa.func.now()),
>   File "<string>", line 8, in create_table
>   File "<string>", line 3, in create_table
>   File "/usr/local/lib/python2.7/dist-packages/alembic/operations/ops.py", line 1098, in create_table
>     return operations.invoke(op)
>   File "/usr/local/lib/python2.7/dist-packages/alembic/operations/base.py", line 318, in invoke
>     return fn(self, operation)
>   File "/usr/local/lib/python2.7/dist-packages/alembic/operations/toimpl.py", line 101, in create_table
>     operations.impl.create_table(table)
>   File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 194, in create_table
>     self._exec(schema.CreateTable(table))
>   File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 118, in _exec
>     return conn.execute(construct, *multiparams, **params)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
>     return meth(self, multiparams, params)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
>     return connection._execute_ddl(self, multiparams, params)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
>     compiled
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
>     context)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1337, in _handle_dbapi_exception
>     util.raise_from_cause(newraise, exc_info)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
>     context)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
>     cursor.execute(statement, parameters)
>   File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 166, in execute
>     result = self._query(query)
>   File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 322, in _query
>     conn.query(q)
>   File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 835, in query
>     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
>   File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1019, in _read_query_result
>     result.read()
>   File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1302, in read
>     first_packet = self.connection._read_packet()
>   File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 981, in _read_packet
>     packet.check_error()
>   File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 393, in check_error
>     err.raise_mysql_exception(self._data)
>   File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
>     raise errorclass(errno, errval)
> oslo_db.exception.DBError: (pymysql.err.InternalError) (1067, u"Invalid default value for 'created_at'") [SQL: u"\nCREATE TABLE opendaylightjournal_new (\n\tseqnum BIGINT NOT NULL AUTO_INCREMENT, \n\tobject_type VARCHAR(36) NOT NULL, \n\tobject_uuid VARCHAR(36) NOT NULL, \n\toperation VARCHAR(36) NOT NULL, \n\tdata BLOB, \n\tstate ENUM('pending','processing','failed','completed') NOT NULL, \n\tretry_count INTEGER, \n\tcreated_at DATETIME DEFAULT now(), \n\tlast_retried TIMESTAMP NULL DEFAULT now(), \n\tPRIMARY KEY (seqnum)\n)ENGINE=InnoDB\n\n"]

Change-Id: Ibad79d0d0ac44c673d57919a37f77c0a24b60451
Closes-bug: #1637272