journal: filter.py: AttributeError: 'NoneType'
The following stack trace occurs.
L3 plugin logs None as http body in journal entry.
So _populate_project_id_and_tenant_id needs to be aware of it.
Otherwise it tries to manipulate on None and trigger following
stack trace.

> ERROR networking_odl.journal.journal [-] Error on run_sync_thread
> TRACE networking_odl.journal.journal Traceback (most recent call last):
> TRACE networking_odl.journal.journal   File "/opt/stack/networking-odl/networking_odl/journal/journal.py", line 153, in run_sync_thread
> TRACE networking_odl.journal.journal     self._sync_pending_rows(session, exit_after_run)
> TRACE networking_odl.journal.journal   File "/opt/stack/networking-odl/networking_odl/journal/journal.py", line 192, in _sync_pending_rows
> TRACE networking_odl.journal.journal     method, urlpath, to_send = self._json_data(row)
> TRACE networking_odl.journal.journal   File "/opt/stack/networking-odl/networking_odl/journal/journal.py", line 128, in _json_data
> TRACE networking_odl.journal.journal     filters.filter_for_odl(row.object_type, row.operation, data)
> TRACE networking_odl.journal.journal   File "/opt/stack/networking-odl/networking_odl/common/filters.py", line 160, in filter_for_odl
> TRACE networking_odl.journal.journal     _populate_project_id_and_tenant_id(data)
> TRACE networking_odl.journal.journal   File "/opt/stack/networking-odl/networking_odl/common/filters.py", line 33, in _populate_project_id_and_tenant_id
> TRACE networking_odl.journal.journal     project_id = resource_dict.get('project_id',
> TRACE networking_odl.journal.journal AttributeError: 'NoneType' object has no attribute 'get'
> TRACE networking_odl.journal.journal

Change-Id: I66c8772fcb58cbf96da06aacae553d007b44ca7f
Closes-Bug: #1632176