use v2 driver for v2 test
V2 driver should be specified for test for v2 driver.

OpenDaylightL3TestCase.test_floatingip_threading complains as follows.
It's because l3 plugin isn't setup properly.
and also ml2 v2 driver isn't used. it should use v2 driver.

> Error during notification for neutron.db.l3_db._notify_routers_callback port, after_delete
> Traceback (most recent call last):
>   File "/networking-odl/.tox/py27/src/neutron/neutron/callbacks/manager.py", line 148, in _notify_loop
>     callback(resource, event, trigger, **kwargs)
>   File "/networking-odl/.tox/py27/src/neutron/neutron/db/l3_db.py", line 1837, in _notify_routers_callback
>     l3plugin.notify_routers_updated(context, router_ids)
> AttributeError: 'NoneType' object has no attribute 'notify_routers_updated'

Change-Id: Id3a02fb27ae35a896c8cbdaee8844cc83b4c35d7
Closes-Bug: #1616558