Use latest networking-sfc release
neutron.db.api was moved from neutron to neutron-lib.
In networking-sfc a fix [1] was implemented and merged. Unit and
functional tests use the latest networking-sfc from git, so they work
fine.

All the non-voting devstack based tempest jobs use the latest released
stable networking-sfc package from pypi (7.0.0), but that version does
not contain the fix [1], which causes the following error during
stack.sh run:

 File "/usr/local/lib/python2.7/dist-packages/networking_sfc/db/flowclassifier_db.py", line 30, in <module>
    from neutron.db import api as db_api
 ImportError: cannot import name api

Now the latest 8.0.0.0b1 release contains the fix already, so let's use
that one to fix all the devstack based jobs.

lower-constraints.txt and requirements.txt had to be also updated
because of neutron as the newer networking-sfc requires 13.0.0.0b2 of
neutron.

[1] I2911249dcb1939366e2c83170defce53092176f9

Change-Id: If59b210b8b9ba5d3d5cf3116b0a4b91dc33952f4